sudo: required
# Install docker into container
services:
  - docker

before_install:
 - docker build -t willdk3000/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true willdk3000/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  # Region specified in AWS Beantalk url
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  # Bucket name = zip file of all github files 
  # Automatically created by AWS Beanstalk : go to AWS S3 Console
  bucket_name: "elasticbeanstalk-us-east-2-681874359244"
  # Name of app
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"