language: generic
sudo: required
# Install docker into container
services:
  - docker

before_install:
 - docker build -t willdk3000/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true willdk3000/docker-react npm run test