version: '3'
services:
  web:
    build:
      # Folder where the source code is
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app